### DISCUSSION TITLE
When is it supported to select aw-server-rust by default after application restart?

### DISCUSSION THREAD

**Discussion by JQiue** [ActivityWatch/activitywatch#1032] [Q&A] [answered]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by ErikBjare** [comment, marked as answer]
You can switch which server is started by modifying the `aw-qt.toml` config file (see https://docs.activitywatch.net/en/latest/directories.html#config for where it is located).

As an example, putting this into your `{config dir}/aw-qt/aw-qt.toml` would do what you want:

```toml
[aw-qt]
autostart_modules = ["aw-server-rust", "aw-watcher-afk", "aw-watcher-window"]
```
