### ISSUE TITLE
Improve CI build times

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#370]
CI build times aren't great right now ("Ran for 38min, Total time 1hr 27min"), and while there isn't much we can do about it, there are a few things:

 - Tests for aw-server-rust require recompiling aw-server-rust (since the executable is built with `--release`)
    - Maybe we shouldn't build with `--release` unless it's actually a release build?
    - The folks at NixOS has had similar issues: https://discourse.nixos.org/t/rust-should-we-build-tests-with-release/2937
 - Currently aw-webui is being built both in aw-server-python and aw-server-rust
    - This will solve itself once we only build one of them.
 - The macOS (~35min) and Windows (~30min) builds seem to take especially long compared to Linux (~20min).
    - This probably just has to do with the overhead/resource restrictions Travis seems to have for builds on non-Linux systems.
 - Make sure that caching works properly.
    - Does it?

We should probably find some way to better benchmark what is actually taking time, so we know where to focus our efforts. All Travis tells us right now is that the `make build` step, for example, takes ~1400s in [the macOS build](https://travis-ci.org/github/ActivityWatch/activitywatch/jobs/661115908).

**Comment by xylix** [comment]
I think caching works "properly", but a part of the problem is that Travis's caches aren't copied over to the test machine disks, they are downloaded as tar:ed artifacts. This means that when we have 1-2 gigs of python / node / rust dependencies, even if we cache some of them there's still quite an overhead.

(For reference: https://docs.travis-ci.com/user/caching/ , especially the part ``` Travis CI saves an archive of all the directories listed in the configuration and uploads it to a storage provider, using a secure and protected URL, ensuring security and privacy of the uploaded archives.

Note that this makes our cache not network-local, it is still bound to network bandwidth and DNS resolutions. That impacts what you can and should store in the cache. If you store archives larger than a few hundred megabytes in the cache, it is unlikely that you’ll see a big speed improvement.```)

Also it is unclear how travis treats git submodules / what happens with caching parts of them. There might actualy be some problems with that, with the naive directory based caching I added.

The points about aw-webui being solved anyway once we only build one server are true. But aw-webui or at least aw-client-js could be improved in some ways. For example we could build and artifactify aw-webui by default and then aw-server-rust (and the python server) could just use the ready-build-aw-webui. Or has this been considered before and seen as something that wouldn't work?

**Comment by xylix** [comment]
Hm I think these https://travis-ci.org/github/ActivityWatch/activitywatch/builds/661160585?utm_medium=notification&utm_source=github_status build failures are from the caches actually being broken somehow. 

I think it's related to the changes I did to the travis cleanup in https://github.com/ActivityWatch/activitywatch/pull/356/files . I was supposed to replace the `skip_cleanup: true` with the newer `cleanup: false` but I just missed them. 

And because travis caches are local to branches this wasn't caught in any of the reviews.

**Comment by ErikBjare** [comment]
We could introduce staged builds using something like this: 
 - https://docs.travis-ci.com/user/build-stages/share-files-s3/
 - https://stackoverflow.com/questions/56208543/travis-stages-for-multiple-os

This would remove the need to build aw-webui on every OS, for example (also reducing CI configuration complexity). Here's an example:

```yaml
stages:
  - build-webui  # builds webui (only on Linux)
  - test         # builds, runs tests, and packages (on all OS's)
  - deploy       # builds package and deploys

jobs:
  include:
  - stage: build-webui
    os: linux
    lang: node
    install:
      - pip install awscli
      - cd ./aw-server/aw-webui; npm install
    script:
      - cd ./aw-server/aw-webui; npm run build
    after_success:
      - aws s3 sync ./aw-server/aw-webui/dist s3://travis-build-stages-shared-storage-test/$TRAVIS_BUILD_NUMBER-webui
    
  # Can stages have matrixes?
  - stage: test
    os: linux
    lang: python
    install:
      - make build
    script:
      - make test

  - stage: test
    os: osx
    osx_image: xcode10.1
    install:
      - make build
    script:
      - make test

  - stage: deploy
    deploy:
      - true   # do deploy stuff
```

I have no idea if this is a good idea or not, nor if it's even worth it, but I thought it was worth mentioning for future consideration.
