### ISSUE TITLE
pyproject.toml build-system should use poetry-core instead of poetry

### ISSUE THREAD

**Issue by huantianad** [ActivityWatch/activitywatch#830]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

The python packages that this project uses all use poetry's build system, and thus all have something like
```toml
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
in their `pyproject.toml` files, which allows the packages to be built via a PEP517 frontend. However, we should instead depend on `poetry-core` instead of `poetry` in the build-system section, as we don't need the CLI tools of poetry to build the package, just the build system. 

```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
Should be used instead.

See <https://github.com/python-poetry/poetry-core#why-is-this-required> for more info.
